### PR TITLE
EaselJS-0.8.1, PreloadJS-0.6.1, SoundJS-0.6.1, TweenJS-0.6.1

### PR DESCRIPTION
**Pull request by hansagames**
I generated externs against newest releases of CreateJSand added small fixes. I tried to leave previous functions and properties order as much as I can, but some of new classes where generated different. I tested it against some of official examples of CreateJS.

### CODE REVIEW

**Comment by Meychi** [comment]
Hey thanks. I'll do quick tests with my current test project and merge if everything seems ok.

**Comment by Meychi** [comment]
Found few minor errors like missing optional params, I'll fix them later. 

Are you using Haxe 3.2.0 as this doesn't work correctly with Haxe 3.1.3.

**Comment by hansagames** [comment]
Yes I use 3.2.0 I think I added Rest parameter and it is not available in 3.1.3.

**Comment by hansagames** [comment]
And there were a lot changes in js externs in 3.2.0. If that is the case we can change them to Dynamic.

**Comment by hansagames** [comment]
Should I remake it for Haxe 3.1.3 ?

**Comment by Meychi** [comment]
Maybe it would be better so. I have my hands full currently so i cant look into it atm.

**Pull request closed without merging**
